info:
  description: Documentation for the Express API
  title: API Documentation
  version: 1.0.0
openapi: 3.1.1
servers:
  - description: API v1
    url: /api/v1
paths:
  /users/create:
    post:
      tags:
        - Users
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCreateResponse"
        "400":
          description: Bad request - validation error
components:
  schemas:
    UserCreateRequest:
      type:
        - object
      properties:
        email:
          type:
            - string
          format: email
        name:
          type:
            - string
          minLength: 1
          maxLength: 255
      required:
        - email
      description: Required data to create a user
      example:
        email: ha@ho.com
        name: Test User
    UserCreateResponse:
      type:
        - object
      properties:
        data:
          type:
            - object
          properties:
            email:
              type:
                - string
              format: email
            name:
              type:
                - string
              minLength: 1
              maxLength: 255
            id:
              type:
                - number
          required:
            - email
            - id
        message:
          type:
            - string
        success:
          default: true
          type:
            - boolean
      required:
        - data
      description: User created successfully
      example:
        data:
          email: ha@ho.com
          id: 1
          name: Test User
        message: Created
        success: true
tags: []
