# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & cache npm deps
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run ESLint checks
        run: npm run lint:check

      - name: Check code formatting
        run: npm run format:check

      - name: Upload node_modules for downstream build
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules

  build:
    needs: quality-checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & cache npm deps
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: node_modules

      - name: Build project
        run: npm run build
